[2025-03-24T12:37:01.077+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T12:37:01.094+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_simple_dbt_dag.transform_data.model1_run manual__2025-03-24T12:36:51+00:00 [queued]>
[2025-03-24T12:37:01.100+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_simple_dbt_dag.transform_data.model1_run manual__2025-03-24T12:36:51+00:00 [queued]>
[2025-03-24T12:37:01.100+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-03-24T12:37:01.109+0000] {taskinstance.py:2890} INFO - Executing <Task(DbtRunLocalOperator): transform_data.model1_run> on 2025-03-24 12:36:51+00:00
[2025-03-24T12:37:01.121+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=193) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T12:37:01.122+0000] {standard_task_runner.py:72} INFO - Started process 195 to run task
[2025-03-24T12:37:01.124+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_simple_dbt_dag', 'transform_data.model1_run', 'manual__2025-03-24T12:36:51+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/my_simple_dbt_dag.py', '--cfg-path', '/tmp/tmp7awarhdy']
[2025-03-24T12:37:01.126+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask transform_data.model1_run
[2025-03-24T12:37:01.175+0000] {task_command.py:467} INFO - Running <TaskInstance: my_simple_dbt_dag.transform_data.model1_run manual__2025-03-24T12:36:51+00:00 [running]> on host cc9050e3ce5a
[2025-03-24T12:37:01.244+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_simple_dbt_dag' AIRFLOW_CTX_TASK_ID='transform_data.model1_run' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T12:36:51+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T12:36:51+00:00'
[2025-03-24T12:37:01.246+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-24T12:37:01.246+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-24T12:37:01.247+0000] {logging_mixin.py:190} INFO - Current task name:transform_data.model1_run state:running start_date:2025-03-24 12:37:01.094964+00:00
[2025-03-24T12:37:01.247+0000] {logging_mixin.py:190} INFO - Dag name:my_simple_dbt_dag and current dag run status:running
[2025-03-24T12:37:01.247+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T12:37:02.422+0000] {local.py:213} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-03-24T12:37:02.423+0000] {local.py:416} INFO - Cloning project to writable temp directory /tmp/tmpoevtb6a3 from /opt/airflow/dags/dbt/dbt_biera
[2025-03-24T12:37:02.423+0000] {local.py:427} INFO - Partial parse is enabled and the latest partial parse file is None
[2025-03-24T12:37:02.424+0000] {config.py:360} INFO - Profile caching is enable.
[2025-03-24T12:37:02.444+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py", line 299, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 708, in build_and_run_cmd
    result = self.run_command(
             ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 524, in run_command
    with self.profile_config.ensure_profile() as profile_values:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 361, in ensure_profile
    cached_profile_path = self._get_profile_path(use_mock_values)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 337, in _get_profile_path
    current_profile_version = self.profile_mapping.version(self.profile_name, self.target_name, use_mock_values)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 98, in version
    profile = self.profile
              ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/postgres/user_pass.py", line 44, in profile
    **self.mapped_params,
      ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 318, in mapped_params
    mapped_params[dbt_field] = self.get_dbt_value(dbt_field)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 295, in get_dbt_value
    value = self._get_airflow_conn_field(airflow_field)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 272, in _get_airflow_conn_field
    value = getattr(self.conn, airflow_field, None)
                    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 146, in conn
    conn = BaseHook.get_connection(self.conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_conn` isn't defined
[2025-03-24T12:37:02.455+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-24T12:37:02.455+0000] {logging_mixin.py:190} INFO - Task start:2025-03-24 12:37:01.094964+00:00 end:2025-03-24 12:37:02.454736+00:00 duration:1.359772
[2025-03-24T12:37:02.455+0000] {logging_mixin.py:190} INFO - Task:<Task(DbtRunLocalOperator): transform_data.model1_run> dag:<DAG: my_simple_dbt_dag> dagrun:<DagRun my_simple_dbt_dag @ 2025-03-24 12:36:51+00:00: manual__2025-03-24T12:36:51+00:00, state:running, queued_at: 2025-03-24 12:36:57.333232+00:00. externally triggered: True>
[2025-03-24T12:37:02.455+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `postgres_conn` isn't defined
[2025-03-24T12:37:02.455+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=my_simple_dbt_dag, task_id=transform_data.model1_run, run_id=manual__2025-03-24T12:36:51+00:00, execution_date=20250324T123651, start_date=20250324T123701, end_date=20250324T123702
[2025-03-24T12:37:02.486+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T12:37:02.486+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task transform_data.model1_run (The conn_id `postgres_conn` isn't defined; 195)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py", line 299, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 708, in build_and_run_cmd
    result = self.run_command(
             ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 524, in run_command
    with self.profile_config.ensure_profile() as profile_values:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 361, in ensure_profile
    cached_profile_path = self._get_profile_path(use_mock_values)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 337, in _get_profile_path
    current_profile_version = self.profile_mapping.version(self.profile_name, self.target_name, use_mock_values)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 98, in version
    profile = self.profile
              ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/postgres/user_pass.py", line 44, in profile
    **self.mapped_params,
      ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 318, in mapped_params
    mapped_params[dbt_field] = self.get_dbt_value(dbt_field)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 295, in get_dbt_value
    value = self._get_airflow_conn_field(airflow_field)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 272, in _get_airflow_conn_field
    value = getattr(self.conn, airflow_field, None)
                    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 146, in conn
    conn = BaseHook.get_connection(self.conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_conn` isn't defined
[2025-03-24T12:37:02.539+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T12:37:02.571+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T12:37:02.574+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
