[2025-03-26T18:33:49.803+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T18:33:49.818+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airbyte-Dag.airbyte_money_json_example manual__2025-03-26T18:33:47.406493+00:00 [queued]>
[2025-03-26T18:33:49.823+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airbyte-Dag.airbyte_money_json_example manual__2025-03-26T18:33:47.406493+00:00 [queued]>
[2025-03-26T18:33:49.824+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-26T18:33:49.834+0000] {taskinstance.py:2890} INFO - Executing <Task(AirbyteTriggerSyncOperator): airbyte_money_json_example> on 2025-03-26 18:33:47.406493+00:00
[2025-03-26T18:33:49.848+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1681) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T18:33:49.849+0000] {standard_task_runner.py:72} INFO - Started process 1683 to run task
[2025-03-26T18:33:49.852+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Airbyte-Dag', 'airbyte_money_json_example', 'manual__2025-03-26T18:33:47.406493+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/meta_ads_dag.py', '--cfg-path', '/tmp/tmp25971kwb']
[2025-03-26T18:33:49.853+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask airbyte_money_json_example
[2025-03-26T18:33:49.905+0000] {task_command.py:467} INFO - Running <TaskInstance: Airbyte-Dag.airbyte_money_json_example manual__2025-03-26T18:33:47.406493+00:00 [running]> on host 929e032a3063
[2025-03-26T18:33:49.973+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rajesh' AIRFLOW_CTX_DAG_ID='Airbyte-Dag' AIRFLOW_CTX_TASK_ID='airbyte_money_json_example' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T18:33:47.406493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T18:33:47.406493+00:00'
[2025-03-26T18:33:49.975+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-26T18:33:49.975+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-26T18:33:49.976+0000] {logging_mixin.py:190} INFO - Current task name:airbyte_money_json_example state:running start_date:2025-03-26 18:33:49.818851+00:00
[2025-03-26T18:33:49.976+0000] {logging_mixin.py:190} INFO - Dag name:Airbyte-Dag and current dag run status:running
[2025-03-26T18:33:49.976+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T18:33:49.983+0000] {base.py:84} INFO - Retrieving connection 'airbyte'
[2025-03-26T18:33:49.996+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 157, in submit_sync_connection
    res = self.airbyte_api.jobs.create_job(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airbyte_api/jobs.py", line 100, in create_job
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airbyte_api/jobs.py", line 94, in create_job
    req = client.prepare_request(requests_http.Request('POST', url, params=query_params, data=data, files=form, headers=headers))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '192.168.1.130/jobs': No scheme supplied. Perhaps you meant https://192.168.1.130/jobs?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 84, in execute
    job_object = hook.submit_sync_connection(connection_id=self.connection_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 165, in submit_sync_connection
    raise AirflowException(e)
airflow.exceptions.AirflowException: Invalid URL '192.168.1.130/jobs': No scheme supplied. Perhaps you meant https://192.168.1.130/jobs?
[2025-03-26T18:33:50.000+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-26T18:33:50.000+0000] {logging_mixin.py:190} INFO - Task start:2025-03-26 18:33:49.818851+00:00 end:2025-03-26 18:33:50.000044+00:00 duration:0.181193
[2025-03-26T18:33:50.000+0000] {logging_mixin.py:190} INFO - Task:<Task(AirbyteTriggerSyncOperator): airbyte_money_json_example> dag:<DAG: Airbyte-Dag> dagrun:<DagRun Airbyte-Dag @ 2025-03-26 18:33:47.406493+00:00: manual__2025-03-26T18:33:47.406493+00:00, state:running, queued_at: 2025-03-26 18:33:47.415788+00:00. externally triggered: True>
[2025-03-26T18:33:50.000+0000] {logging_mixin.py:190} INFO - Failure caused by Invalid URL '192.168.1.130/jobs': No scheme supplied. Perhaps you meant https://192.168.1.130/jobs?
[2025-03-26T18:33:50.001+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=Airbyte-Dag, task_id=airbyte_money_json_example, run_id=manual__2025-03-26T18:33:47.406493+00:00, execution_date=20250326T183347, start_date=20250326T183349, end_date=20250326T183350
[2025-03-26T18:33:50.020+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T18:33:50.020+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 63 for task airbyte_money_json_example (Invalid URL '192.168.1.130/jobs': No scheme supplied. Perhaps you meant https://192.168.1.130/jobs?; 1683)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 157, in submit_sync_connection
    res = self.airbyte_api.jobs.create_job(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airbyte_api/jobs.py", line 100, in create_job
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airbyte_api/jobs.py", line 94, in create_job
    req = client.prepare_request(requests_http.Request('POST', url, params=query_params, data=data, files=form, headers=headers))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '192.168.1.130/jobs': No scheme supplied. Perhaps you meant https://192.168.1.130/jobs?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 84, in execute
    job_object = hook.submit_sync_connection(connection_id=self.connection_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 165, in submit_sync_connection
    raise AirflowException(e)
airflow.exceptions.AirflowException: Invalid URL '192.168.1.130/jobs': No scheme supplied. Perhaps you meant https://192.168.1.130/jobs?
[2025-03-26T18:33:50.063+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T18:33:50.094+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T18:33:50.100+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
